### PR TITLE
Opinionated Repository Reconstruction

### LINKED ISSUE #10: Repository Re-construction
This is just a suggestion. If you don't want to do this, you can just close this issue as 'not planned'.

I think this repository has few minor structural problems.

* Duplicated files like [`DarkModeCS.cs`](https://github.com/BlueMystical/Dark-Mode-Forms/blob/main/DarkModeCS.cs) and [`DarkModeCS.cs`](https://github.com/BlueMystical/Dark-Mode-Forms/blob/main/Example/DarkModeForms/DarkModeCS.cs)
* Lack of 'coding style guideline' like `.editorconfig`  
  VS supports additional `.editorconfig` entries
* Included files that aren't needed to repository  
  Why do we have [`DarkModeForms_v1.3.1.zip`](https://github.com/BlueMystical/Dark-Mode-Forms/blob/main/Example/DarkModeForms/DarkModeForms_v1.3.1.zip) in this repository?

This makes me hard to contribute to this repository. Editing files in VS will reformat everything to my coding style, so I have to modify them via notepad which prevents me from using 'code completion', 'error detection' etc. that VS provides.

So I suggest re-constructing this respository to make this repository to be easy to maintain and easy to contribute.

---

## Move 'Example' to the top

First, we have to move 'Example' project to root directory.

```plaintext
<root>
├ .git
├ Properties
├ Resources
│ 
│ DarkModeForms.sln
│ README.md
└ (and other files)
```

## Create centralized 'DarkModeForms' library directory

Then, create 'DarkModeForms' directory that contains every library files that this repository provides:
* [`DarkModeCS.cs`](https://github.com/BlueMystical/Dark-Mode-Forms/blob/main/Example/DarkModeForms/DarkModeCS.cs)
* [`FlatComboBox.cs`](https://github.com/BlueMystical/Dark-Mode-Forms/blob/main/Example/DarkModeForms/FlatComboBox.cs)
* [`FlatTabControl.cs`](https://github.com/BlueMystical/Dark-Mode-Forms/blob/main/Example/DarkModeForms/FlatTabControl.cs)
* [`Messenger.cs`](https://github.com/BlueMystical/Dark-Mode-Forms/blob/main/Example/DarkModeForms/Messenger.cs)

```plaintext
<root>
├ .git
├ DarkModeForms
│ │ DarkModeCS.cs
│ │ FlatComboBox.cs
│ │ FlatTabControl.cs
│ └ Messenger.cs
├ Properties
├ Resources
│ 
│ DarkModeForms.sln
│ README.md
└ (and other files)
```

Every modifications for this library files must be done in these files under 'DarkModeForms' directory only. Duplicated files must not be created.

With this, we can 'focus' contribution and distribution on these files.

## Create `.editorconfig` and `.gitignore`

After that, we now create `.editorconfig` and `.gitignore` files.

VS supports `.editorconfig` configuration by default. You can create your own `.editorconfig` file at the root of this repository, or refer to my own [`.editorconfig`](https://github.com/TetraTheta/Small-Projects/blob/main/Pathed/.editorconfig) as an example.  
My `.editorconfig` file is nested and minified, so it lacks of 'root' configuration and comments. I can provide 'merged' version of my `.editorconfig`s, if you want.

You have to include the newly created `.editorconfig` file to the project, if you didn't create it within VS.

`.gitignore` makes Git to ignore files, so that they won't be uploaded or tracked. I suggest you to use [`.gitignore` generated with Toptal](https://www.toptal.com/developers/gitignore/api/rider,csharp,intellij+all,visualstudio,visualstudiocode,archive,archives), but you can make your own `.gitignore` with [this](https://www.toptal.com/developers/gitignore?templates=rider,csharp,intellij+all,visualstudio,visualstudiocode,archive,archives).

## Reformat every files in VS

Since we have `.editorconfig` file that controls coding style, you should reformat every files in your project via VS. If your VS recognizes `.editorconfig`, style of those codes should be changed consistently.

## Remove excessive files from Git index

Since we now have `.gitignore`, we can safely remove files that should not be tracked from Git index.
```bash
# This commands are for Bash
# Move to repository root
# If you use Windows, use 'cd /d "C:\path\to\repo\root"' instead
cd "/path/to/repo/root"
# Untrack everything from Git index temporarily
# git command will work on any OS if installed correctly
git rm --cached -r .
# Re-add important files to Git index
git add .
```
These commands won't remove physical files, so don't worry. No files will be edited or be removed. These commands will only modify Git index.

## Check before commit/push

If you have Git GUI, you can easily check how files will be modified or be removed/created within GUI. That will help you from fixing problems before pushing your commit to GitHub.

## Push!

If you think everything is OK, you can push your commits to GitHub.

## Publishing

When you want to publish new version, just zip 'DarkModeForms' that has library files and upload it. Since it is the only source of your library, everything would be up-to-date.

---

I tried to do it myself and create a PR, but I'm afraid that it will enforce you (and everyone) to use my coding style, and you might be uncomfortable with my coding style.  
Best way of adapting this is, you configure your own coding style and apply it.

If you have any question about this re-construction, feel free to ask me about it. I'll help as much as I can.

### PR DESCRIPTION
**Pull request by TetraTheta**
This is very opinionated repository reconstruction suggestion.

* namespace is changed to `DarkModeForms`
* `.editorconfig` is generated by me, and modified to my preferences.
* excessive imports are removed
* and so on... (sorry, I don't remember all 😞)

Since I didn't run full-reformat, so there should be some codes that doesn't comply with `.editorconfig` configurations.

Will close #10 

---

Please use Git command line, and don't use GitHub's 'Uploade Files' feature. It is always advised to clone-edit-commit-push when using GitHub.

### CODE REVIEW

**Comment by TetraTheta** [comment]
I just found few more files that needs manual reformatting... Please wait.

**Comment by TetraTheta** [comment]
I modified few more files. All tabs should be replaced to spaces.

**Comment by BlueMystical** [comment]
Everything seems to be alright, thanks Tetra.

**Comment by kachnitata** [comment]
nice!.
Although the editorconfig differs from my personal style, I can happily live with it - the benefit of automatic reformatting and unification is worth it.

BTW, DarkModeCS.cs contains three more classes: OSThemeColors, MyRenderer, CustomColorTable. Shouldn't we split them into their respective files? This would make the code a tiny bit clearer and perhaps sligtly reduce the chance of merge conflicts...

**Comment by TetraTheta** [comment]
`DarkModeCS.cs` file serves as 'minimal' dependency. I think those classes are needed for its purpose.

> No Nuggets, No external DLLs, Just 1 File: [DarkModeCS.cs](https://github.com/BlueMystical/Dark-Mode-Forms/blob/main/SourceFiles/DarkModeCS.cs) Copy/Paste or [Download](https://github.com/BlueMystical/Dark-Mode-Forms/releases/latest) and import it into your project.

**Comment by kachnitata** [comment]
>Just 1 File

I can see the point. On the other hand, `FlatTabControl `(but not `FlatComboBox `and `Messenger`) is still directly referenced from `DarkModeCS.cs` and is required for the code to compile, isn't it?

**Comment by kachnitata** [comment]
I think it would be possible to get rid of this dependency using reflection but is is probably not worth it

**Comment by kachnitata** [comment]
I managed to connect to Github directly from my VS, thanks to @TetraTheta's reconstruction and suggestions it was even easier.
I sent my first Pull Request - I guess it is a good practice to create one per issue, so that they can be approved/rejected independently. But is it a good idea to create another one while the current one is still pending? Because all my edits are so far in the same file (although they are mutually independent) and I do not create separate branch for each of the edits, would it work out well? wouldn't it cause mess if, for example, one of my pull requests gets rejected but the following ones also contained the same code modification?

**Comment by TetraTheta** [comment]
I always prefer 'per-topic PR' like this PR. All of my changes were for 'reconstructing this repository', so I put all of my modifications into a single PR.

> But is it a good idea to create another one while the current one is still pending?

Git (and GitHub) are smart enough to determine if the PR is mergeable or not. All those changes are handled as 'diff'. You can see diff of this PR [here](https://github.com/BlueMystical/Dark-Mode-Forms/pull/15/files). If there is any conflict between your PR and the current main branch, GitHub will instruct you on how to manually resolve it.

If PR B depends on PR A, mentioning 'This PR depends on PR A' in the description is enough, I think. But you have to keep the 'base branch'(PR A branch) up-to-date and merge its changes into the PR B branch often. If the diff are too large, they cannot be automatically merged, so manual resolution must be required.

This is why I said 'create branch per PR' before. Separating branches will make things easier to organize.

In this case, if PR A is rejected, you'll have to choose between 'Remove rejected part from PR B' or 'Close PR B'. If the dependency on PR A is a crucial part of PR B, PR B should also be closed.

Note that all of these are just my opinions.

---

@BlueMystical Can you open Discussion for this repository? It should be under 'General' on the repository settings page.

I think this kind of chat, which is not directly related to the current issue or PR, should go into the Discussion section instead.

If you don't like it, you can use third-party services like [Gitter](https://gitter.im/).

**Pull request merged**
