### PR TITLE
fix for #23

### PR DESCRIPTION
**Pull request by MagicAndre1981**
ok, I made a fix for #23 which handles dark/light theme change. 

You need to update your Forms to inherit from `DarkModeBaseForm` (`public partial class Form1 : DarkModeBaseForm`) and in Constructor assign dm variable` base.dm = new DarkModeCS(this);`. 

I've added an enum of the Theme (Dark/Light/FollowSystem) and depending on this setting the form is rendered in this theme. 

 ```c#
public enum DarkModePolicy
{
        FollowSystemTheme = 0,
        ForceLightTheme = 1,
        ForceDarkTheme = 2
}
```

I've updated the demo to have a radiobutton group to switch between mode.

### CODE REVIEW

**Comment by BlueMystical** [comment]
the Theme Swapping Group Options are not working on my side:
image

**Comment by MagicAndre1981** [comment]
ok, I see this, too. Any ideas? I call ApplyTheme with the correct bool parameter . Maybe rebase of your changes deleted something in my code I added 🤷‍♂️

**Comment by MagicAndre1981** [comment]
ok, I had to move the OSColor init because I got a NRE, maybe this broke it.

**Comment by BlueMystical** [comment]
i.. dont know....  a reverted version still shows this problem...
gotta digg furter in to find the cause.

Sorry i had to revert your code, will apply it back once i catch the bug

**Comment by BlueMystical** [comment]
Found it!  its this line of code:
image
i dont remeber making that..
but comenting it restores the functionality so..

**Comment by BlueMystical** [comment]
All is restored to your last Commit.
all i did afterwards was comment that line.
Gonna investigate further what that method does,
in the meanwhile, Functionality is restored, woohooo!

**Comment by MagicAndre1981** [comment]
> Gonna investigate further what that method does, in the meanwhile, Functionality is restored, woohooo!

ok, came from a [commit at beginning of this month](https://github.com/BlueMystical/Dark-Mode-Forms/commit/b7cb43aa658374ca8810e001ceb5d330604fe79e) from @kachnitata in #55, not from my code:

image

**Comment by MagicAndre1981** [comment]
ok, the purpose of this PR #55 was to exclude controls from Dark mode, so what you saw in your picture 🫣

**Pull request merged**
