### PR TITLE
Catch up changes

### PR DESCRIPTION
**Pull request by imerzan**

### CODE REVIEW

**Comment by kachnitata** [comment]
Hi @imerzan  what's the reason you removed lot of my code changes without any notice? Did they cause any problems to you?
After your modification, the library is not usable anymore to me :-(

**Comment by kachnitata** [comment]
I hope it was just an unintentional mistake, prehaps you based your PR on a very old version of the files

**Comment by imerzan** [comment]
Error while I was fetching upstream changes disregard

**Comment by BlueMystical** [comment]
i had not approved any PRs that i remember...

**Pull request closed without merging**
