### PR TITLE
ignore dark mode for selected control

### PR DESCRIPTION
**Pull request by kachnitata**
extracted ExcludeFromProcessing,
fixed ControlsProcessed unwanted re-initialization,

this should solve #52 

also renamed an (unrelated) variable that was hiding a field, for better code clarity

### CODE REVIEW

**Comment by kachnitata** [comment]
succesfully tested in my own project but I haven't included it in the demo here...

**Comment by panyann** [comment]
Hi, when I excluded the button like so:
`DarkModeCS.ExcludeFromProcessing(btnDropTables);`
It mostly worked correctly, but didn't change the text color, it was still white... Maybe it's something to improve?

**Comment by panyann** [comment]
🙂
I create the button with the designer. It has a "Flat" FlatStyle, maybe it can mess up something...

image

Also maybe it's important - it's inside a TabControl.
Thanks in advance for trying, but if it can't be done don't worry too much 👍

**Comment by kachnitata** [comment]
I tried to put a button in the demo Form1 included in the sources.
But it works as expected, even in a TabPage.... there must be something else...

image

**Comment by kachnitata** [comment]
also with FlatStyle = Flat

image

**Comment by kachnitata** [comment]
Hi @panyann. In my former experiment, I used by mistake a disabled `Button` but when I enabled it, I can see the issue, too.
The problem is that although the Button is really excluded from `ThemeControl()` (as can be confirmed by stepping through the code), if it uses `SystemColors.ControlText` as foreground, the color is still changed to light via the shared `SystemColors` palette.
I think the only reasonable workaround for you is to set the `ForeColor` explicitely to, for example, `System.Drawing.Color.Black`.
That works for me.

**Comment by panyann** [comment]
Hey, thanks for your help @kachnitata, I will check this out, when I'll be back at work.

**Pull request merged**
